services:
    peer0:
        build: .
        command:
            [
                "0.0.0.0:8000",
                "peer1:8001",
                "peer2:8002",
                "peer3:8003",
                "peer4:8004",
                "1.0",
            ]
        networks:
            - gossip_net
        ports:
            - "8000:8000"

    peer1:
        build: .
        command:
            [
                "0.0.0.0:8001",
                "peer0:8000",
                "peer2:8002",
                "peer3:8003",
                "peer4:8004",
                "None",
            ]
        networks:
            - gossip_net
        ports:
            - "8001:8001"

    peer2:
        build: .
        command:
            [
                "0.0.0.0:8002",
                "peer0:8000",
                "peer1:8001",
                "peer3:8003",
                "peer4:8004",
                "None",
            ]
        networks:
            - gossip_net
        ports:
            - "8002:8002"

    peer3:
        build: .
        command:
            [
                "0.0.0.0:8003",
                "peer0:8000",
                "peer1:8001",
                "peer2:8002",
                "peer4:8004",
                "None",
            ]
        networks:
            - gossip_net
        ports:
            - "8003:8003"

    peer4:
        build: .
        command:
            [
                "0.0.0.0:8004",
                "peer0:8000",
                "peer1:8001",
                "peer2:8002",
                "peer3:8003",
                "None",
            ]
        networks:
            - gossip_net
        ports:
            - "8004:8004"

networks:
    gossip_net:
        driver: bridge
