services:
  peer0:
    build: .
    command: ["0.0.0.0:8000", "peer1:8001", "1.0"]
    networks:
      - net
    ports:
      - "8000:8000"

  peer1:
    build: .
    command: ["0.0.0.0:8001", "peer0:8000", "peer2:8002", "1e-09"]
    networks:
      - net
    ports:
      - "8001:8001"

  peer2:
    build: .
    command: ["0.0.0.0:8002", "peer1:8001", "1e-09"]
    networks:
      - net
    ports:
      - "8002:8002"

networks:
  net:
    driver: bridge
